### ISSUE TITLE
Support Linux / Non-Apple platforms

### ISSUE THREAD

**Issue by sliemeobn** [scchn/swift-zpl#2]
First of all: thanks for creating this package!

A few commands (mainly around GraphicField/image conversion) rely on CoreGraphics, which is only available on Apple platforms.

It would be great to only conditionally depend on these, and maybe add "raw" support for images on other platforms (without automatic conversions).

**Comment by scchn** [comment]
Thanks!

I have no experience reading images on other platforms, I can only add some compilation conditions for Apple platforms.

Please feel free to create a pull request if you know how to implement this feature.

**Comment by sliemeobn** [comment]
I see you already added conditional imports! 🙏

If you are ok with a breaking the public API a tiny bit I would suggest keeping the `GraphicField` type free of non-portable types, and only provide a bunch of (conditional) convenience initializers.

That way the same type can live on all platforms, but if `CoreGraphics` is available you can use your awesome conversion magic from `CGImage`.

Another benefit this potentially has is that we could have an initializer with just `Data` and size, and I would even offer one with the pre-encoded `string` that is used in ZPL instead of raw bytes.

I think the use case exists where it makes sense to just hard-code a pre-converted ZPL-string of a logo or something. 

On the type itself I would simply store size and stringified data.

Let me know what you think, I am happy to provide a PR if you agree (might take a few weeks though).

**Comment by scchn** [comment]
You are welcome to create a PR.

Our apps only use `UIImage` to create `GraphicField`, so I didn't think of creating other initializers.
It would be great to make all commands available on all platforms.
